
# Notas e Moedas
n = float(input())

print("NOTAS:")
dinheiro = int(n/100)
n -= int(dinheiro*100)
print("{} nota(s) de R$ 100.00".format(dinheiro))
dinheiro = int(n/50)
n -= int(dinheiro*50)
print("{} nota(s) de R$ 50.00".format(dinheiro))
dinheiro = int(n/20)
n -= int(dinheiro*20)
print("{} nota(s) de R$ 20.00".format(dinheiro))
dinheiro = int(n/20)
n -= int(dinheiro*20)
print("{} nota(s) de R$ 10.00".format(dinheiro))
dinheiro = int(n/5)
n -= int(dinheiro*5)
print("{} nota(s) de R$ 5.00".format(dinheiro))
dinheiro = int(n/2)
n -= int(dinheiro*2)
print("{} nota(s) de R$ 2.00".format(dinheiro))

print("MOEDAS:")
dinheiro = int(n/1)
n -= float(dinheiro*1)
print("{} moeda(s) de R$ 1.00".format(int(dinheiro)))
dinheiro = int(n/0.50)
n -= float(dinheiro*0.50)
print("{} moeda(s) de R$ 0.50".format(int(dinheiro)))
dinheiro = int(n/0.25)
n -= float(dinheiro*0.25)
print("{} moeda(s) de R$ 0.25".format(int(dinheiro)))
dinheiro = int(n/0.10)
n -= float(dinheiro*0.10)
print("{} moeda(s) de R$ 0.10".format(int(dinheiro)))
dinheiro = int(n/0.05)
n -= float(dinheiro*0.05)
print("{} moeda(s) de R$ 0.05".format(int(dinheiro)))
dinheiro = int(n/0.01)
n -= float(dinheiro*0.01)
print("{} moeda(s) de R$ 0.01".format(int(dinheiro)))
